
import "./globals.css";


export const metadata = {
  title: "Movie App",
  description: "Generated by Simge DURU",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body className={"bg-[#03071E] text-white"}>
        <div className="h-full mt-5">
          {children}
        </div>
      </body>
    </html>
  );
}
